site_name: HKUST ENTERPRIZE RM2027 Tutorial Site
site_description: ENTERPRIZE tutorials
site_url: https://tutorial.robomaster.hk/
repo_name: hkustenterprize/RM2027-Tutorial-Pages
repo_url: https://github.com/hkustenterprize/RM2027-Tutorial-Pages
edit_uri: edit/main/docs/

theme:
  name: material
  language: zh
  logo: assets/enterprize-logo.png
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  features:
    - content.code.copy
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest

plugins:
  - search:
      lang:
        - zh
        - en

nav:
  - 首页: index.md
  - 机械:
      - 机械部门主页: Mechanical/index.md
  - 硬件:
      - 硬件部门主页: Hardware/index.md
  - 嵌入式:
      - 嵌入式部门主页: Embedded/index.md
      - 开发环境配置:
          - Windows: "Embedded/Environment/Windows/index.md"
          - macOS: "Embedded/Environment/macOS/index.md"
          - Linux: "Embedded/Environment/Linux/index.md"
          - 环境验证: "Embedded/Environment/Verify/index.md"

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
